package pojo;
// Generated 31 Oct, 2018 2:21:46 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;

/**
 * Question generated by hbm2java
 */
// Entity
// Table(name = "question", catalog = "rmi")
public class Question implements java.io.Serializable {

	private Integer qid;
	private int subid;
	private int tid;
	private int qtype;
	private int qlevel;
	private int marks;
	private String qquestion;
	private String qoption;
	private String qsolution;
	private boolean qgraded;
	private Date qcreationdate;

	public Question() {
	}

	public Question(int subid, int tid, int qtype, int qlevel, int marks, String qquestion, String qsolution,
			boolean qgraded, Date qcreationdate) {
		this.subid = subid;
		this.tid = tid;
		this.qtype = qtype;
		this.qlevel = qlevel;
		this.marks = marks;
		this.qquestion = qquestion;
		this.qsolution = qsolution;
		this.qgraded = qgraded;
		this.qcreationdate = qcreationdate;
	}

	public Question(int subid, int tid, int qtype, int qlevel, int marks, String qquestion, String qoption,
			String qsolution, boolean qgraded, Date qcreationdate) {
		this.subid = subid;
		this.tid = tid;
		this.qtype = qtype;
		this.qlevel = qlevel;
		this.marks = marks;
		this.qquestion = qquestion;
		this.qoption = qoption;
		this.qsolution = qsolution;
		this.qgraded = qgraded;
		this.qcreationdate = qcreationdate;
	}

	// Id
	// GeneratedValue(strategy = IDENTITY)

	// Column(name = "marks", nullable = false)
	public int getMarks() {
		return this.marks;
	}

	// Temporal(TemporalType.TIMESTAMP)
	// Column(name = "qcreationdate", nullable = false, length = 19)
	public Date getQcreationdate() {
		return this.qcreationdate;
	}

	// Column(name = "qid", unique = true, nullable = false)
	public Integer getQid() {
		return this.qid;
	}

	// Column(name = "qlevel", nullable = false)
	public int getQlevel() {
		return this.qlevel;
	}

	// Column(name = "qoption", length = 2000)
	public String getQoption() {
		return this.qoption;
	}

	// Column(name = "qquestion", nullable = false, length = 2000)
	public String getQquestion() {
		return this.qquestion;
	}

	// Column(name = "qsolution", nullable = false, length = 5000)
	public String getQsolution() {
		return this.qsolution;
	}

	// Column(name = "qtype", nullable = false)
	public int getQtype() {
		return this.qtype;
	}

	// Column(name = "subid", nullable = false)
	public int getSubid() {
		return this.subid;
	}

	// Column(name = "tid", nullable = false)
	public int getTid() {
		return this.tid;
	}

	// Column(name = "qgraded", nullable = false)
	public boolean isQgraded() {
		return this.qgraded;
	}

	public void setMarks(int marks) {
		this.marks = marks;
	}

	public void setQcreationdate(Date qcreationdate) {
		this.qcreationdate = qcreationdate;
	}

	public void setQgraded(boolean qgraded) {
		this.qgraded = qgraded;
	}

	public void setQid(Integer qid) {
		this.qid = qid;
	}

	public void setQlevel(int qlevel) {
		this.qlevel = qlevel;
	}

	public void setQoption(String qoption) {
		this.qoption = qoption;
	}

	public void setQquestion(String qquestion) {
		this.qquestion = qquestion;
	}

	public void setQsolution(String qsolution) {
		this.qsolution = qsolution;
	}

	public void setQtype(int qtype) {
		this.qtype = qtype;
	}

	public void setSubid(int subid) {
		this.subid = subid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

}
