package pojo;
// Generated 8 Nov, 2018 11:29:30 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Solution generated by hbm2java
 */
// Entity
// Table(name = "solution", catalog = "rmi")
public class Solution implements java.io.Serializable {

	private SolutionId id;
	private String quesid;
	private int sid;
	private String solution;
	private boolean status;
	private Date starttime;
	private Date lastsubmit;

	public Solution() {
	}

	public Solution(SolutionId id, String quesid, int sid, boolean status) {
		this.id = id;
		this.quesid = quesid;
		this.sid = sid;
		this.status = status;
	}

	public Solution(SolutionId id, String quesid, int sid, String solution, boolean status, Date starttime,
			Date lastsubmit) {
		this.id = id;
		this.quesid = quesid;
		this.sid = sid;
		this.solution = solution;
		this.status = status;
		this.starttime = starttime;
		this.lastsubmit = lastsubmit;
	}

	// EmbeddedId

	// AttributeOverrides({ //AttributeOverride(name = "pid", column = //Column(name
	// = "pid", nullable = false)),
	// AttributeOverride(name = "uid", column = //Column(name = "uid", nullable =
	// false)) })
	public SolutionId getId() {
		return this.id;
	}

	// Temporal(TemporalType.TIMESTAMP)
	// Column(name = "lastsubmit", length = 19)
	public Date getLastsubmit() {
		return this.lastsubmit;
	}

	// Column(name = "quesid", nullable = false, length = 10000)
	public String getQuesid() {
		return this.quesid;
	}

	// Column(name = "sid", nullable = false)
	public int getSid() {
		return this.sid;
	}

	// Column(name = "solution", length = 20000)
	public String getSolution() {
		return this.solution;
	}

	// Temporal(TemporalType.TIMESTAMP)
	// Column(name = "starttime", length = 19)
	public Date getStarttime() {
		return this.starttime;
	}

	// Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setId(SolutionId id) {
		this.id = id;
	}

	public void setLastsubmit(Date lastsubmit) {
		this.lastsubmit = lastsubmit;
	}

	public void setQuesid(String quesid) {
		this.quesid = quesid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	public void setSolution(String solution) {
		this.solution = solution;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
