package pojo;
// Generated 31 Oct, 2018 2:21:46 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;

/**
 * Substudent generated by hbm2java
 */
// Entity
// Table(name = "substudent", catalog = "rmi")
public class Substudent implements java.io.Serializable {

	private SubstudentId id;
	private Date substudentcreationdate;

	public Substudent() {
	}

	public Substudent(SubstudentId id, Date substudentcreationdate) {
		this.id = id;
		this.substudentcreationdate = substudentcreationdate;
	}

	// EmbeddedId

	// AttributeOverrides({ //AttributeOverride(name = "sid", column = //Column(name
	// = "sid", nullable = false)),
	// AttributeOverride(name = "subid", column = //Column(name = "subid", nullable
	// = false)) })
	public SubstudentId getId() {
		return this.id;
	}

	// Temporal(TemporalType.TIMESTAMP)
	// Column(name = "substudentcreationdate", nullable = false, length = 19)
	public Date getSubstudentcreationdate() {
		return this.substudentcreationdate;
	}

	public void setId(SubstudentId id) {
		this.id = id;
	}

	public void setSubstudentcreationdate(Date substudentcreationdate) {
		this.substudentcreationdate = substudentcreationdate;
	}

}
