package pojo;
// Generated 31 Oct, 2018 2:21:46 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;

/**
 * Subteacher generated by hbm2java
 */
// Entity
// Table(name = "subteacher", catalog = "rmi")
public class Subteacher implements java.io.Serializable {

	private SubteacherId id;
	private Date subteachercreationdate;

	public Subteacher() {
	}

	public Subteacher(SubteacherId id, Date subteachercreationdate) {
		this.id = id;
		this.subteachercreationdate = subteachercreationdate;
	}

	// EmbeddedId

	// AttributeOverrides({ //AttributeOverride(name = "tid", column = //Column(name
	// = "tid", nullable = false)),
	// AttributeOverride(name = "subid", column = //Column(name = "subid", nullable
	// = false)) })
	public SubteacherId getId() {
		return this.id;
	}

	// Temporal(TemporalType.TIMESTAMP)
	// Column(name = "subteachercreationdate", nullable = false, length = 19)
	public Date getSubteachercreationdate() {
		return this.subteachercreationdate;
	}

	public void setId(SubteacherId id) {
		this.id = id;
	}

	public void setSubteachercreationdate(Date subteachercreationdate) {
		this.subteachercreationdate = subteachercreationdate;
	}

}
