package pojo;
// Generated 31 Oct, 2018 2:21:46 PM by Hibernate Tools 5.1.7.Final

/**
 * SubteacherId generated by hbm2java
 */
// Embeddable
public class SubteacherId implements java.io.Serializable {

	private int tid;
	private int subid;

	public SubteacherId() {
	}

	public SubteacherId(int tid, int subid) {
		this.tid = tid;
		this.subid = subid;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubteacherId))
			return false;
		SubteacherId castOther = (SubteacherId) other;

		return (this.getTid() == castOther.getTid()) && (this.getSubid() == castOther.getSubid());
	}

	// Column(name = "subid", nullable = false)
	public int getSubid() {
		return this.subid;
	}

	// Column(name = "tid", nullable = false)
	public int getTid() {
		return this.tid;
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTid();
		result = 37 * result + this.getSubid();
		return result;
	}

	public void setSubid(int subid) {
		this.subid = subid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

}
