package pojo;
// Generated 31 Oct, 2018 2:21:46 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;

/**
 * Teacherreg generated by hbm2java
 */
// Entity
// Table(name = "teacherreg", catalog = "rmi", uniqueConstraints =
// //UniqueConstraint(columnNames = "temail"))
public class Teacherreg implements java.io.Serializable {

	private Integer tid;
	private String tname;
	private String temail;
	private boolean tstatus;
	private String tpassword;
	private Date tcreationdate;

	public Teacherreg() {
	}

	public Teacherreg(String tname, String temail, boolean tstatus, String tpassword, Date tcreationdate) {
		this.tname = tname;
		this.temail = temail;
		this.tstatus = tstatus;
		this.tpassword = tpassword;
		this.tcreationdate = tcreationdate;
	}

	// Id
	// GeneratedValue(strategy = IDENTITY)

	// Temporal(TemporalType.TIMESTAMP)
	// Column(name = "tcreationdate", nullable = false, length = 19)
	public Date getTcreationdate() {
		return this.tcreationdate;
	}

	// Column(name = "temail", unique = true, nullable = false, length = 200)
	public String getTemail() {
		return this.temail;
	}

	// Column(name = "tid", unique = true, nullable = false)
	public Integer getTid() {
		return this.tid;
	}

	// Column(name = "tname", nullable = false, length = 100)
	public String getTname() {
		return this.tname;
	}

	// Column(name = "tpassword", nullable = false, length = 50)
	public String getTpassword() {
		return this.tpassword;
	}

	// Column(name = "tstatus", nullable = false)
	public boolean isTstatus() {
		return this.tstatus;
	}

	public void setTcreationdate(Date tcreationdate) {
		this.tcreationdate = tcreationdate;
	}

	public void setTemail(String temail) {
		this.temail = temail;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	public void setTpassword(String tpassword) {
		this.tpassword = tpassword;
	}

	public void setTstatus(boolean tstatus) {
		this.tstatus = tstatus;
	}

}
