package clientswing;

import java.awt.event.ActionEvent;
import java.util.List;

import javax.swing.JFrame;
//latest
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;

import common.AddI;
import common.AddO;
import pojo.Subteacher;
import pojo.Teacherreg;

/**
 *
 * @author naruto
 */
public class Addpaperques extends javax.swing.JFrame {

	/**
	 * Creates new form genresult
	 * 
	 * @param server2
	 * @param server1
	 * @param serverObj
	 * @param user
	 * @param subs
	 */
	List<Object> subs = null;
	String[] subjects = null;
	Teacherreg user = null;
	AddO server1, server2;
	private AddI serverObj;
	private String selectedSubject;

	public Addpaperques(List<Object> subs, Teacherreg user, AddI serverObj, AddO server1, AddO server2) {
		this.subs = subs;
		this.user = user;
		this.server1 = server1;
		this.server2 = server2;
		this.serverObj = serverObj;
		this.subjects = new String[this.subs.size() + 1];
		this.subjects[0] = "----------";
		for (int i = 1; i <= this.subs.size(); i++) {
			subjects[i] = Integer.toString(((Subteacher) this.subs.get(i - 1)).getId().getSubid());

		}

		initComponents();
		  setTitle("WELCOME TO ONLINE QUIZ SYSTEM ");
	}

	public void setParentFrame(JFrame f) {
		parent = f;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		setExtendedState(MAXIMIZED_BOTH);
		;
		Submit = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		back = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		Submit.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		Submit.setText("Submit");
		Submit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SubmitActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		jLabel3.setText("Username:");

		jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		jLabel4.setText(user.getTname());

		back.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		back.setText("Back");
		back.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		jLabel1.setText("Subject:");

		jComboBox1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(subjects));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(19, 19, 19)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(37, 37, 37).addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE,
												80, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel4).addComponent(jComboBox1,
														javax.swing.GroupLayout.PREFERRED_SIZE, 105,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(29, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(16, 16, 16)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(jLabel3))
						.addGap(35, 35, 35)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(126, 126, 126)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(back).addComponent(Submit))
						.addContainerGap(27, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
		parent.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_formWindowClosing

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
		selectedSubject = (String) jComboBox1.getSelectedItem();
	}// GEN-LAST:event_jComboBox1ActionPerformed

	private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SubmitActionPerformed
		if (jComboBox1.getSelectedIndex() < 1) {
			JOptionPane.showMessageDialog(this, "Please Select a subject to continue", "Warning",
					JOptionPane.ERROR_MESSAGE);
		} else {
			Addpaper f = new Addpaper(user, selectedSubject, serverObj, server1, server2);
			f.setLocationRelativeTo(null);
			f.setParentFrame(parent);
			f.setVisible(true);
			((TeacherMain) parent).setChild(f);
			dispose();
		} // GEN-LAST:event_SubmitActionPerformed
	}

	private void backActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backActionPerformed
		parent.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_backActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton Submit;
	private javax.swing.JButton back;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	// End of variables declaration//GEN-END:variables
	private javax.swing.JFrame parent;

	public void actionPerformed(ActionEvent e) {

	}

}
