package clientswing;

import java.awt.Frame;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import common.AddI;
import common.AddO;

public class MainFrame extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */
	AddI serverObj = null;
	JFrame f;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAdministration;
	private javax.swing.JButton btnExamination;
	private javax.swing.JButton btnRegistration;

	private javax.swing.JLabel lblTitle;

	// End of variables declaration//GEN-END:variables
	private JFrame child;
	private AddO server1;

	private AddO server2;
	boolean serverflag = false;
	/**
	 * Creates new form MainFrame
	 * @param serverflag 
	 * 
	 * @param server
	 * @param server22
	 * @param server1flag
	 */
	public MainFrame(AddI serverObj, AddO server1, AddO server2, boolean serverflag) {
		this.serverflag = serverflag;
		this.serverObj = serverObj;
		this.server1 = server1;
		this.server2 = server2;
		initComponents();
		
	}

	private void btnAdministrationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAdministrationActionPerformed
		LoginFrame f = new LoginFrame("admin", this.serverObj, this.server1, this.server2);
		f.setLocationRelativeTo(null);
		f.setParentFrame(this);
		f.setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_btnAdministrationActionPerformed

	private void btnExaminationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExaminationActionPerformed
		LoginFrame f = new LoginFrame("student", this.serverObj, this.server1, this.server2);
		f.setLocationRelativeTo(null);
		f.setParentFrame(this);
		f.setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_btnExaminationActionPerformed

	private void btnRegistrationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegistrationActionPerformed
		RegistrationFrame f = new RegistrationFrame(this.serverObj, this.server1, this.server2);
		f.setLocationRelativeTo(null);
		f.setParentFrame(this);
		f.setVisible(true);
		f.setExtendedState(MAXIMIZED_BOTH);
		this.setVisible(false);
	}// GEN-LAST:event_btnRegistrationActionPerformed

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		setExtendedState(Frame.MAXIMIZED_BOTH);
		if(!this.serverflag) {	JOptionPane.showMessageDialog(this, "No Server Available Please Try Again Later");
		}else {
		lblTitle = new javax.swing.JLabel();
		btnRegistration = new javax.swing.JButton();
		btnExamination = new javax.swing.JButton();
		btnAdministration = new javax.swing.JButton();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Online Quiz System");
		setResizable(false);

		lblTitle.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
		lblTitle.setText("Welcome to Online Quiz System");

		btnRegistration.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
		btnRegistration.setText("Registration");
		btnRegistration.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRegistrationActionPerformed(evt);
			}
		});

		btnExamination.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
		btnExamination.setText("Login");
		btnExamination.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExaminationActionPerformed(evt);
			}
		});

		btnAdministration.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
		btnAdministration.setText("Administration");
		btnAdministration.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAdministrationActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(47, 47, 47).addComponent(lblTitle))
						.addGroup(layout.createSequentialGroup().addGap(224, 224, 224)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(btnAdministration, javax.swing.GroupLayout.DEFAULT_SIZE, 177,
												Short.MAX_VALUE)
										.addComponent(btnRegistration, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnExamination, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
				.addContainerGap(38, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(21, 21, 21).addComponent(lblTitle).addGap(41, 41, 41)
						.addComponent(btnRegistration).addGap(38, 38, 38).addComponent(btnExamination)
						.addGap(40, 40, 40).addComponent(btnAdministration).addContainerGap(48, Short.MAX_VALUE)));

		pack();}
	}// </editor-fold>//GEN-END:initComponents

	public void setChild(JFrame child) {
		this.child = child;
	}

}
