package clientswing;

import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import common.AddI;
import common.AddO;
import pojo.Subteacher;
import pojo.Teacherreg;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author naruto
 */
public class Questionpanelold extends javax.swing.JFrame implements ActionListener {
	// private JFrame f1;
	List<Object> subs = null;
	String[] subjects = null;
	Teacherreg user = null;
	private String selectedSubject;
	private AddI serverObj;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JRadioButton Rbmultians;
	private javax.swing.JRadioButton Rbmultitype;
	private javax.swing.JRadioButton Rbsubjetivetype;
	private javax.swing.JButton Submit;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButton1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	// End of variables declaration//GEN-END:variables
	private javax.swing.JFrame parent;

	/**
	 * Creates new form NewJFrame
	 * 
	 * @param subs2
	 * @param serverObj
	 * @param server2
	 * @param server1
	 */
	AddO server1, server2;

	public Questionpanelold(List<Object> subs, Teacherreg user, AddI serverObj, AddO server1, AddO server2) {
		this.subs = subs;
		this.user = user;
		this.server1 = server1;
		this.server2 = server2;
		this.serverObj = serverObj;
		this.subjects = new String[this.subs.size() + 1];
		this.subjects[0] = "----------";
		for (int i = 1; i <= subs.size(); i++) {
			subjects[i] = Integer.toString(((Subteacher) subs.get(i - 1)).getId().getSubid());

		}
		initComponents();
		Submit.addActionListener(this);
		Rbmultitype.addActionListener(this);
		Rbmultians.addActionListener(this);
		Rbsubjetivetype.addActionListener(this);

	}

	@Override
	public void actionPerformed(ActionEvent e) {

		if (e.getSource() == Submit) {
			if (Rbmultitype.isSelected()) {

				Multitype f = new Multitype(user, selectedSubject, serverObj, server1, server2);
				f.setExtendedState(Frame.MAXIMIZED_BOTH);
				f.setParentFrame(parent);
				f.setVisible(true);
				((TeacherMain) parent).setChild(f);
				dispose();
			} else if (Rbmultians.isSelected()) {
				selectedSubject = jComboBox1.getSelectedItem().toString();
				System.out.println(selectedSubject);
				Multianswer f = new Multianswer(user, selectedSubject, serverObj, server1, server2);
				f.setExtendedState(Frame.MAXIMIZED_BOTH);
				f.setParentFrame(parent);
				f.setVisible(true);
				((TeacherMain) parent).setChild(f);
				dispose();
			} //
			else if (Rbsubjetivetype.isSelected()) {

				Subjectivetype f = new Subjectivetype(user, selectedSubject, serverObj, server1, server2);
				f.setExtendedState(Frame.MAXIMIZED_BOTH);
				f.setParentFrame(parent);
				f.setVisible(true);
				((TeacherMain) parent).setChild(f);
				dispose();
			}
		}

	}

	// private void addActionPerformed(java.awt.event.ActionEvent evt) {//
	// GEN-FIRST:event_addActionPerformed
	// // TODO add your handling code here:
	// jComboBox1.addItem(tfaddsubject.getText());
	// }// GEN-LAST:event_addActionPerformed

	private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing

		// TODO add your handling code here:
		parent.setVisible(true);
		this.dispose();

	}// GEN-LAST:event_formWindowClosing

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		Rbmultitype = new javax.swing.JRadioButton();
		Rbsubjetivetype = new javax.swing.JRadioButton();
		Rbmultians = new javax.swing.JRadioButton();
		Submit = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		jLabel1.setText("Subject:");

		jComboBox1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(subjects));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		buttonGroup1.add(Rbmultitype);
		Rbmultitype.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		Rbmultitype.setText("Multiple type answer");
		Rbmultitype.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				RbmultitypeActionPerformed(evt);
			}
		});

		buttonGroup1.add(Rbsubjetivetype);
		Rbsubjetivetype.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		Rbsubjetivetype.setText("Subjective answer");
		Rbsubjetivetype.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				RbsubjetivetypeActionPerformed(evt);
			}
		});

		buttonGroup1.add(Rbmultians);
		Rbmultians.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		Rbmultians.setText("Multianswer");
		Rbmultians.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				RbmultiansActionPerformed(evt);
			}
		});

		Submit.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		Submit.setText("Submit");

		jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		jLabel3.setText("Username:");

		jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		jLabel4.setText("username");

		jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		jLabel2.setText("Choose type:");

		jButton1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
		jButton1.setText("Back");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(19, 19, 19)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(
												Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(50, 50, 50))
								.addGroup(layout.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel2).addComponent(jLabel3))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel4)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(Rbmultitype,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(Rbsubjetivetype,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(Rbmultians,
																javax.swing.GroupLayout.PREFERRED_SIZE, 164,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 105,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(117, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(16, 16, 16)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(jLabel3))
						.addGap(35, 35, 35)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(30, 30, 30)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(Rbmultitype, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2))
						.addGap(18, 18, 18)
						.addComponent(Rbsubjetivetype, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(Rbmultians, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(Submit, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
		// TODO add your handling code here:
		selectedSubject = jComboBox1.getSelectedItem().toString();
		// JOptionPane.showMessageDialog(this, selectedSubject);

	}// GEN-LAST:event_jComboBox1ActionPerformed

	private void RbmultiansActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RbmultiansActionPerformed
		// TODO add your handling code here:
		Rbsubjetivetype.setSelected(false);
		Rbmultitype.setSelected(false);
	}// GEN-LAST:event_RbmultiansActionPerformed

	private void RbmultitypeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RbmultitypeActionPerformed
		// TODO add your handling code here:
		Rbsubjetivetype.setSelected(false);
		Rbmultians.setSelected(false);
	}// GEN-LAST:event_RbmultitypeActionPerformed

	private void RbsubjetivetypeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RbsubjetivetypeActionPerformed
		// TODO add your handling code here:
		Rbmultians.setSelected(false);
		Rbmultitype.setSelected(false);

	}// GEN-LAST:event_RbsubjetivetypeActionPerformed

	public void setParentFrame(JFrame f) {
		parent = f;
	}

	private void tfaddsubjectActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfaddsubjectActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_tfaddsubjectActionPerformed

}
