package pojo;
// Generated 11 Nov, 2018 9:22:47 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paperreg generated by hbm2java
 */
@Entity
@Table(name = "paperreg", catalog = "rmi")
public class Paperreg implements java.io.Serializable {

	private Integer pid;
	private int subid;
	private int tid;
	private int l1m1;
	private int l1m2;
	private int l1m3;
	private int l1m4;
	private int l2m1;
	private int l2m2;
	private int l2m3;
	private int l2m4;
	private int l3m1;
	private int l3m2;
	private int l3m3;
	private int l3m4;
	private String passkey;
	private Date pcreationdate;
	private Date pstarttime;
	private Date endtime;

	public Paperreg() {
	}

	public Paperreg(int subid, int tid, int l1m1, int l1m2, int l1m3, int l1m4, int l2m1, int l2m2, int l2m3, int l2m4,
			int l3m1, int l3m2, int l3m3, int l3m4, String passkey, Date pcreationdate) {
		this.subid = subid;
		this.tid = tid;
		this.l1m1 = l1m1;
		this.l1m2 = l1m2;
		this.l1m3 = l1m3;
		this.l1m4 = l1m4;
		this.l2m1 = l2m1;
		this.l2m2 = l2m2;
		this.l2m3 = l2m3;
		this.l2m4 = l2m4;
		this.l3m1 = l3m1;
		this.l3m2 = l3m2;
		this.l3m3 = l3m3;
		this.l3m4 = l3m4;
		this.passkey = passkey;
		this.pcreationdate = pcreationdate;
	}

	public Paperreg(int subid, int tid, int l1m1, int l1m2, int l1m3, int l1m4, int l2m1, int l2m2, int l2m3, int l2m4,
			int l3m1, int l3m2, int l3m3, int l3m4, String passkey, Date pcreationdate, Date pstarttime, Date endtime) {
		this.subid = subid;
		this.tid = tid;
		this.l1m1 = l1m1;
		this.l1m2 = l1m2;
		this.l1m3 = l1m3;
		this.l1m4 = l1m4;
		this.l2m1 = l2m1;
		this.l2m2 = l2m2;
		this.l2m3 = l2m3;
		this.l2m4 = l2m4;
		this.l3m1 = l3m1;
		this.l3m2 = l3m2;
		this.l3m3 = l3m3;
		this.l3m4 = l3m4;
		this.passkey = passkey;
		this.pcreationdate = pcreationdate;
		this.pstarttime = pstarttime;
		this.endtime = endtime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pid", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "subid", nullable = false)
	public int getSubid() {
		return this.subid;
	}

	public void setSubid(int subid) {
		this.subid = subid;
	}

	@Column(name = "tid", nullable = false)
	public int getTid() {
		return this.tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}

	@Column(name = "l1m1", nullable = false)
	public int getL1m1() {
		return this.l1m1;
	}

	public void setL1m1(int l1m1) {
		this.l1m1 = l1m1;
	}

	@Column(name = "l1m2", nullable = false)
	public int getL1m2() {
		return this.l1m2;
	}

	public void setL1m2(int l1m2) {
		this.l1m2 = l1m2;
	}

	@Column(name = "l1m3", nullable = false)
	public int getL1m3() {
		return this.l1m3;
	}

	public void setL1m3(int l1m3) {
		this.l1m3 = l1m3;
	}

	@Column(name = "l1m4", nullable = false)
	public int getL1m4() {
		return this.l1m4;
	}

	public void setL1m4(int l1m4) {
		this.l1m4 = l1m4;
	}

	@Column(name = "l2m1", nullable = false)
	public int getL2m1() {
		return this.l2m1;
	}

	public void setL2m1(int l2m1) {
		this.l2m1 = l2m1;
	}

	@Column(name = "l2m2", nullable = false)
	public int getL2m2() {
		return this.l2m2;
	}

	public void setL2m2(int l2m2) {
		this.l2m2 = l2m2;
	}

	@Column(name = "l2m3", nullable = false)
	public int getL2m3() {
		return this.l2m3;
	}

	public void setL2m3(int l2m3) {
		this.l2m3 = l2m3;
	}

	@Column(name = "l2m4", nullable = false)
	public int getL2m4() {
		return this.l2m4;
	}

	public void setL2m4(int l2m4) {
		this.l2m4 = l2m4;
	}

	@Column(name = "l3m1", nullable = false)
	public int getL3m1() {
		return this.l3m1;
	}

	public void setL3m1(int l3m1) {
		this.l3m1 = l3m1;
	}

	@Column(name = "l3m2", nullable = false)
	public int getL3m2() {
		return this.l3m2;
	}

	public void setL3m2(int l3m2) {
		this.l3m2 = l3m2;
	}

	@Column(name = "l3m3", nullable = false)
	public int getL3m3() {
		return this.l3m3;
	}

	public void setL3m3(int l3m3) {
		this.l3m3 = l3m3;
	}

	@Column(name = "l3m4", nullable = false)
	public int getL3m4() {
		return this.l3m4;
	}

	public void setL3m4(int l3m4) {
		this.l3m4 = l3m4;
	}

	@Column(name = "passkey", nullable = false, length = 10)
	public String getPasskey() {
		return this.passkey;
	}

	public void setPasskey(String passkey) {
		this.passkey = passkey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pcreationdate", nullable = false, length = 19)
	public Date getPcreationdate() {
		return this.pcreationdate;
	}

	public void setPcreationdate(Date pcreationdate) {
		this.pcreationdate = pcreationdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pstarttime", length = 19)
	public Date getPstarttime() {
		return this.pstarttime;
	}

	public void setPstarttime(Date pstarttime) {
		this.pstarttime = pstarttime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endtime", length = 19)
	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

}
