package pojo;
// Generated 11 Nov, 2018 9:22:47 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SolutionId generated by hbm2java
 */
@Embeddable
public class SolutionId implements java.io.Serializable {

	private int pid;
	private int uid;

	public SolutionId() {
	}

	public SolutionId(int pid, int uid) {
		this.pid = pid;
		this.uid = uid;
	}

	@Column(name = "pid", nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "uid", nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SolutionId))
			return false;
		SolutionId castOther = (SolutionId) other;

		return (this.getPid() == castOther.getPid()) && (this.getUid() == castOther.getUid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPid();
		result = 37 * result + this.getUid();
		return result;
	}

}
