package pojo;
// Generated 11 Nov, 2018 9:22:47 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SubstudentId generated by hbm2java
 */
@Embeddable
public class SubstudentId implements java.io.Serializable {

	private int sid;
	private int subid;

	public SubstudentId() {
	}

	public SubstudentId(int sid, int subid) {
		this.sid = sid;
		this.subid = subid;
	}

	@Column(name = "sid", nullable = false)
	public int getSid() {
		return this.sid;
	}

	public void setSid(int sid) {
		this.sid = sid;
	}

	@Column(name = "subid", nullable = false)
	public int getSubid() {
		return this.subid;
	}

	public void setSubid(int subid) {
		this.subid = subid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubstudentId))
			return false;
		SubstudentId castOther = (SubstudentId) other;

		return (this.getSid() == castOther.getSid()) && (this.getSubid() == castOther.getSubid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSid();
		result = 37 * result + this.getSubid();
		return result;
	}

}
