package pojo;
// Generated 11 Nov, 2018 9:22:47 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Teacherreg generated by hbm2java
 */
@Entity
@Table(name = "teacherreg", catalog = "rmi", uniqueConstraints = @UniqueConstraint(columnNames = "temail"))
public class Teacherreg implements java.io.Serializable {

	private Integer tid;
	private String tname;
	private String temail;
	private boolean tstatus;
	private String tpassword;
	private Date tcreationdate;

	public Teacherreg() {
	}

	public Teacherreg(String tname, String temail, boolean tstatus, String tpassword, Date tcreationdate) {
		this.tname = tname;
		this.temail = temail;
		this.tstatus = tstatus;
		this.tpassword = tpassword;
		this.tcreationdate = tcreationdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tid", unique = true, nullable = false)
	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	@Column(name = "tname", nullable = false, length = 100)
	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	@Column(name = "temail", unique = true, nullable = false, length = 200)
	public String getTemail() {
		return this.temail;
	}

	public void setTemail(String temail) {
		this.temail = temail;
	}

	@Column(name = "tstatus", nullable = false)
	public boolean isTstatus() {
		return this.tstatus;
	}

	public void setTstatus(boolean tstatus) {
		this.tstatus = tstatus;
	}

	@Column(name = "tpassword", nullable = false, length = 50)
	public String getTpassword() {
		return this.tpassword;
	}

	public void setTpassword(String tpassword) {
		this.tpassword = tpassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tcreationdate", nullable = false, length = 19)
	public Date getTcreationdate() {
		return this.tcreationdate;
	}

	public void setTcreationdate(Date tcreationdate) {
		this.tcreationdate = tcreationdate;
	}

}
